name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - mkdocs.yml
      - .github/workflows/docs.yml
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - SECURITY.md
      - CHANGELOG.md
      - README.md

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v3
      - run: |
          uv python install
          uv run mkdocs gh-deploy --force
