name: Edge Container Build

on:
  repository_dispatch:
    types: [edge-build]

permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  IMAGE_NAME: shinybrar/skaha
  IMAGE_TAG: edge

jobs:
  edge-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Client Payload
        run: |
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
      -
        name: Checkout Code
        uses: actions/checkout@v4.2.1
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          install: true
      -
        name: Perform Dockerhub Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Perform GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build & Push Docker Image
        id: build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          target: production
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          push: true
          labels: |
            org.opencontainers.image.title=skaha
            org.opencontainers.image.version=edge
            org.opencontainers.image.description='Python Client for CANFAR Science Portal'
            org.opencontainers.image.licenses=AGPL-3.0
            org.opencontainers.image.source=https://github.com/shinybrar/skaha
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      -
        name: Attest GHCR Container Image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      -
        name: Attest Dockerhub Container Image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
